# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: vscode-sqlite CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install
      run: |
        npm install
        npm run install-html
    - name: Build
      run: |
        npm run compile
        npm run build-html
    - name: Test
      run: |
        npm run test
        npm run test-html
    - name: Package
      run: npm run package
    - name: Get version
      run: ::set-env name=VERSION::$(node -p -e "require('./package.json').version")
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: vscode-sqlite-${{ env.VERSION }}
        path: vscode-sqlite-${{ env.VERSION }}.vsix
      env:
        CI: true
