name: Publish

on:
  release:
    types: [ published ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Package
      run: npm run package
    - name: Get version
      run: echo ::set-env name=VERSION::$(node -p -e "require('./package.json').version")
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: vscode-sqlite-${{ env.VERSION }}
        path: vscode-sqlite-${{ env.VERSION }}.vsix