name: Publish

on:
  release:
    types: [ published ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Set environment variables
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
        OVSX_PAT: ${{ secrets.OVSX_PAT }}
    - name: Install vsce and ovsx
      run: npm install --global vsce ovsx
    - name: Install
      run: |
        npm install
        npm run install-html
    - name: Publish to Visual Studio Marketplace
      run: vsce publish
    - name: Publish to Eclipse Open VSX
      run: ovsx publish